<?php

include_once 'fns/get_revisions.php';
$revisions = get_revisions();

header('Content-Type: text/html; charset=UTF-8');

echo '<!DOCTYPE html>'
    .'<html>'
        .'<head>'
            .'<title>Speedometer</title>'
            .'<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />'
            .'<meta name="viewport" content="width=device-width, user-scalable=no" />'
            .'<link rel="icon" type="image/png"'
            .' href="images/icons/16.png?'.$revisions['images/icons/16.png'].'" />'
            .'<link rel="icon" type="image/png" sizes="32x32"'
            .' href="images/icons/32.png?'.$revisions['images/icons/32.png'].'" />'
            .'<link rel="icon" type="image/png" sizes="64x64"'
            .' href="images/icons/64.png?'.$revisions['images/icons/64.png'].'" />'
            .'<link rel="icon" type="image/png" sizes="90x90"'
            .' href="images/icons/90.png?'.$revisions['images/icons/90.png'].'" />'
            .'<link rel="icon" type="image/png" sizes="120x120"'
            .' href="images/icons/120.png?'.$revisions['images/icons/120.png'].'" />'
            .'<link rel="icon" type="image/png" sizes="128x128"'
            .' href="images/icons/128.png?'.$revisions['images/icons/128.png'].'" />'
            .'<link rel="icon" type="image/png" sizes="256x256"'
            .' href="images/icons/256.png?'.$revisions['images/icons/256.png'].'" />'
            .'<link rel="icon" type="image/png" sizes="512x512"'
            .' href="images/icons/512.png?'.$revisions['images/icons/512.png'].'" />'
            .'<link rel="stylesheet" type="text/css" href="index.css?7" />'
        .'</head>'
        .'<body>'
            .'<img id="logoImage" src="images/icons/128.png?'.$revisions['images/icons/128.png'].'" />'
            .'<h1>Speedometer</h1>'
            .'<div>A GPS tracker app.</div>'
            .'<a class="button" href="run/">Launch</a>'
            .'<button disabled="disabled" class="button" id="installButton">Install</button>'
            .'<h2>Description</h2>'
            .'<div id="description">'
                .'Speedometer uses GPS to show the speed.'
                .' It also shows how long and how far you went,'
                .' what were your maximum and average speeds,'
                .' what is your current altitude, where are you heading to'
                .' and what where your minimum and maximum altitudes during the trip.'
                .' These features make it suitable for walking,'
                .' running, riding a bike or a car.'
                .' Speedometer supports both imperial and metric unit systems, dark and light themes.'
                .' Source code is available on'
                .' <a href="https://github.com/Qliavi/speedometer/">GitHub</a>.'
                .' Licensed under AGPL (version 3 or later).'
            .'</div>'
            .'<div>'
                .'<br />'
                .'<a href="http://qliavi.com/">qliavi.com</a>'
            .'</div>'
            .'<script type="text/javascript" src="index.js?1"></script>'
        .'</body>'
    .'</html>';
